point = { x = [1,3], y = 2 }
[valores_CN]
#ANICONS = "https://i.imgur.com/A2pPOED.png"
BADGER = "https://i.imgur.com/Sxif9mN.jpg"
BADGES = "https://i.imgur.com/9iaKE6b.png"
SNOWY = "https://i.imgur.com/KxcqKpJ.gif"
SNOW = "https://i.imgur.com/mpOU7Ca.gif"
HSNOW = "https://i.imgur.com/i5dLK8G.gif"
BSNOW = "https://i.imgur.com/4B1xuMw.gif"
SUICONS = "https://i.imgur.com/cM95ybG.jpg"
ANICONS = "https://i.imgur.com/bmUoCIb.png"
SUPPLY = "https://i.imgur.com/PWreEK2.gif"
PARADRP = "https://i.imgur.com/ShQMIoU.png"
LAND = "https://i.imgur.com/Cmyq9vd.jpg"
LANDER = "https://i.imgur.com/lc5s0OJ.jpg"
YELLOW = "https://imgur.com/dzM9NtT.jpg"
WHITE = "https://imgur.com/khohhCw.jpg"
RED = "https://imgur.com/IMcwSAq.jpg"
[folha_CN]
ANICONS = [5, 4]
SUICONS = [8, 4]
LAND = [4,8]
LANDER = [8,8]
YELLOW = [8,16]
BADGES = [6, 8]
#CROW = [1,1]
[valores_Missao]
ANIMAL = "https://i.imgur.com/BivOv8y.jpg"
AVENTURA = "https://imgur.com/CqlwpCh.jpg"
MISSAO = "https://imgur.com/aFuEYkS.jpg"
EVENTO = "https://imgur.com/qa5FFq3.jpg"
[folha_Missao]
ANIMAL = [3,1]
AVENTURA = [2,1]
MISSAO = [6,3]
EVENTO = [6,3]
[c_POOL]
img=".i.CN._LANDER.5"
e_mbio = {img=".i.Missao._MISSAO.0", x=100, y=100, w=300, h=500, o=0.4}
e_matm = {img=".i.Missao._MISSAO.3", x=200, y=100, w=300, h=500, o=0.4}
e_mxpr = {img=".i.Missao._MISSAO.6", x=200, y=100, w=300, h=500, o=0.4}
e_mcli = {img=".i.Missao._MISSAO.9", x=400, y=100, w=300, h=500, o=0.4}
e_mfri = {img=".i.Missao._MISSAO.12", x=500, y=100, w=300, h=500, o=0.4}
e_mgeo = {img=".i.Missao._MISSAO.15", x=600, y=100, w=300, h=500, o=0.4}

e_mper = {img=".i.Missao._EVENTO.0", x=700, y=100, w=300, h=500, o=0.4}
e_menc = {img=".i.Missao._EVENTO.3", x=700, y=100, w=300, h=500, o=0.4}
e_msup = {img=".i.Missao._EVENTO.6", x=900, y=100, w=300, h=500, o=0.4}
e_mdes = {img=".i.Missao._EVENTO.9", x=1000, y=100, w=300, h=500, o=0.4}
e_msal = {img=".i.Missao._EVENTO.12", x=1100, y=100, w=300, h=500, o=0.4}
e_mcai = {img=".i.Missao._EVENTO.15", x=1200, y=100, w=300, h=500, o=0.4}
[valores_PUZZLE]
Weather = "https://i.imgur.com/kYFntfo.gif"
Baloon = "https://i.imgur.com/kYFntfo.gif"
Seals ="https://i.imgur.com/09geayY.gif"
Seal ="https://i.imgur.com/09geayY.gif"
[folha_PUZZLE]
Weather = [4,3]
Baloon = [5,5]
Seals = [5, 5]
Seal = [4, 4]
[l_BIO]
img =".i.CN._LANDER.0"
index = [3,3]

[l_YEL]
img =".i.CN._YELLOW.0"
index = [6,5]

[s_ROOT]
img =".i.CN._LANDER.0"
index = [0,1,2,3]
[c_SEAL]
img = ".i.CN._YELLOW.0"
direita=".i.ROOTzz0.0.0"

p_seal = {img=".i.PUZZLE._Seal.0", pr=1, foi=".i.ROOTzz0.0.0" , texto = "Observação da foca completada!"}
[c_SEALS]
img = ".i.CN._YELLOW.1"
direita=".i.ROOTzz0.0.0"

p_seals = {img=".i.PUZZLE._Seals.0", pr=2, foi=".i.ROOTzz0.0.0" , texto = "Observação da foca completada!"}
[c_BALOON]
img=".i.CN._LANDER.1"
direita=".i.ROOTzz0.0.0"
p_balooni = {img=".i.PUZZLE._Baloon.0", pr=7, foi=".i.ROOTzz0.0.0" , texto = "Missão meteorológica completada!"}
t_BAL = {tit = "solta o balaão", txt="monta o qc"}
[c_BALOONI]
img=".i.CN._LANDER.1"
direita=".i.ROOTzz0.0.0"
t_BOI = {tit = "solta o balaão", txt="monta o qc"}
p_baloon = {img=".i.PUZZLE._Weather.0", pr=6, foi=".i.ROOTzz0.0.0" , texto = "Missão meteorológica completada!"}
[c_ROOT0]
img=".i.CN._LANDER.0"
t_BALO = {tit = "solta o balaão", txt="monta o qc"}

[e_WLC]
tit = "ola"
txt = "todos"
pr = 3
A = "nuvem"
B = "nuv"
C = "nu"
Z ="B"
foi = ".i.ROOTzz3.0.0"
[mapa_YEL]
We = {local=[1,1], tit="Aqui teremos o lançamento de um balão", texto="lançar um balão!", foi=".i.BALOONI"}
Ae = {local=[2,2], tit="Aqui teremos o lançamento de um balão", texto="lançar um balão!", foi=".i.BALOON"}
Be = {local=[3,3], tit="Aqui acompanharemos o crescimento de uma foca", texto="Observar uma foca bebê!", foi=".i.SEAL"}
Bs = {local=[4,0], tit="Aqui acompanharemos o crescimento de uma foca", texto="Observar uma foca bebê!", foi=".i.SEALS"}

[s_Bioma]
img =".i.CN._LANDER.0"
index = [4,5,6,7]
[e_supri]
img="*fa fa-parachute-box fa-5x"
x=900
y=300
texto="Os suprimentos cairam nesta direção"
cena=".i.ROOTzz1.0.0"
foi=".i.Biomazz4.0.0"
[e_base]
img="*fa fa-campground fa-5x"
x=900
y=300
texto="Voltaremos ao campo base"
cena=".i.Biomazz5.0.0"
foi=".i.ROOTzz0.0.0"
[e_ani]
img=".i.Missao._ANIMAL.0"
x=100
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="Lista de missões"
tit="Lista de missões"
foi=".i.ROOT0.0.0"
#foi=".i.POOL.0.0"
[e_adv]
img=".i.Missao._AVENTURA.0"
x=500
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="A missão inicia aqui"
tit="A missão inicia aqui"
foi=".i.BIOzz0zz1.0.0"
[e_adt]
img=".i.Missao._AVENTURA.1"
x=900
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="Outra missão inicia aqui"
tit="Outra missão inicia aqui"
foi=".i.YELzz0zz1.0.0"
